// <auto-generated />

#nullable disable

namespace EvolutionaryArchitecture.Fitnet.Reports.Infrastructure.Persistence.Migrations;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

[DbContext(typeof(ReportsDbContext))]
[Migration("20260228125721_InitialReportsSchema")]
partial class InitialReportsSchema
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("Reports")
            .HasAnnotation("ProductVersion", "10.0.1")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("EvolutionaryArchitecture.Fitnet.Reports.Domain.ReportGeneration", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<DateTime>("GeneratedAt")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");

                b.ToTable("ReportGenerations", "Reports");
            });

        modelBuilder.Entity("EvolutionaryArchitecture.Fitnet.Reports.Infrastructure.Outbox.Outbox", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Payload")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<DateTime?>("ProcessedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Type")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id");

                b.ToTable("OutboxMessages", "Reports");
            });

        modelBuilder.Entity("EvolutionaryArchitecture.Fitnet.Reports.Infrastructure.Saga.ReportGenerationSaga", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<Guid>("CorrelationId")
                    .HasColumnType("uuid");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");

                b.HasIndex("CorrelationId")
                    .IsUnique();

                b.ToTable("ReportGenerationSagas", "Reports");
            });
#pragma warning restore 612, 618
    }
}
